FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY apps/api/package.json ./apps/api/package.json
RUN npm install
COPY . .
RUN npm run build -w apps/api
CMD ["npm","run","start:dev","-w","apps/api"]
