FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY apps/web/package.json ./apps/web/package.json
RUN npm install
COPY . .
RUN npm run build -w apps/web
CMD ["npm","run","dev","-w","apps/web"]
